In [12]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib

In [14]:
df = pd.read_parquet('../dataset/processed/cleaned_data.parquet')

In [15]:
# df = pd.read_parquet('https://github.com/iamnitishsah/FoodOps.AI/raw/refs/heads/main/DeliveryOps/data/processed/cleaned_data.parquet')

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 195788 entries, 0 to 195787
Data columns (total 25 columns):
 #   Column                                        Non-Null Count   Dtype
---  ------                                        --------------   -----
 0   market_id                                     195788 non-null  float64
 1   created_at                                    195788 non-null  datetime64[us]
 2   actual_delivery_time                          195788 non-null  datetime64[us]
 3   store_id                                      195788 non-null  int64
 4   store_primary_category                        195788 non-null  str
 5   order_protocol                                195788 non-null  float64
 6   total_items                                   195788 non-null  int64
 7   subtotal                                      195788 non-null  int64
 8   num_distinct_items                            195788 non-null  int64
 9   min_item_price                                195788 non-null  int64
 10  max_item_price                                195788 non-null  int64
 11  total_onshift_dashers                         195788 non-null  float64
 12  total_busy_dashers                            195788 non-null  float64
 13  total_outstanding_orders                      195788 non-null  float64
 14  estimated_order_place_duration                195788 non-null  int64
 15  estimated_store_to_consumer_driving_duration  195788 non-null  float64
 16  market_id_imputed                             195788 non-null  bool
 17  store_category_imputed                        195788 non-null  bool
 18  total_onshift_dashers_imputed                 195788 non-null  bool
 19  total_busy_dashers_imputed                    195788 non-null  bool
 20  total_outstanding_orders_imputed              195788 non-null  bool
 21  total_delivery_duration                       195788 non-null  float64
 22  created_at_local                              195788 non-null  datetime64[us, US/Pacific]
 23  order_hour                                    195788 non-null  int32
 24  order_day_of_week                             195788 non-null  int32
dtypes: bool(5), datetime64[us, US/Pacific](1), datetime64[us](2), float64(7), int32(2), int64(7), str(1)
memory usage: 30.6 MB

In [17]:
df.sample(10)

,market_id,created_at,actual_delivery_time,store_id,store_primary_category,order_protocol,total_items,subtotal,num_distinct_items,min_item_price,max_item_price,total_onshift_dashers,total_busy_dashers,total_outstanding_orders,estimated_order_place_duration,estimated_store_to_consumer_driving_duration,market_id_imputed,store_category_imputed,total_onshift_dashers_imputed,total_busy_dashers_imputed,total_outstanding_orders_imputed,total_delivery_duration,created_at_local,order_hour,order_day_of_week
46419,6.00,2015-02-15 22:29:06,2015-02-15 23:29:33,6497,indian,3.00,3,1097,2,199,699,22.00,17.00,19.00,251,488.00,False,False,True,True,True,"3,627.00",2015-02-15 14:29:06-08:00,14,6
95293,6.00,2015-01-29 02:37:58,2015-01-29 03:58:06,3144,unknown,2.00,2,2200,2,1025,1175,58.00,56.00,84.00,251,273.00,True,True,True,True,True,"4,808.00",2015-01-28 18:37:58-08:00,18,2
121638,4.00,2015-02-13 20:10:08,2015-02-13 20:46:09,2056,chinese,3.00,2,2090,2,750,1295,66.00,65.00,96.00,251,522.00,False,False,False,False,False,"2,161.00",2015-02-13 12:10:08-08:00,12,4
19524,2.00,2015-02-11 17:30:53,2015-02-11 18:05:44,6865,mexican,5.00,7,4969,5,275,1199,13.00,13.00,16.00,251,267.00,False,False,False,False,False,"2,091.00",2015-02-11 09:30:53-08:00,9,2
33598,6.00,2015-01-24 16:53:44,2015-01-24 17:16:38,2142,vietnamese,1.00,2,1700,1,700,700,9.00,8.00,6.00,446,322.00,False,False,True,True,True,"1,374.00",2015-01-24 08:53:44-08:00,8,5
96086,2.00,2015-01-29 04:07:14,2015-01-29 04:39:44,1365,pizza,3.00,2,1449,2,599,850,44.00,37.00,50.00,251,641.00,False,False,False,False,False,"1,950.00",2015-01-28 20:07:14-08:00,20,2
50738,1.00,2015-01-22 02:47:22,2015-01-22 03:31:45,4898,dessert,4.00,3,4065,3,695,2175,43.00,43.00,59.00,251,562.00,False,False,False,False,False,"2,663.00",2015-01-21 18:47:22-08:00,18,2
110806,4.00,2015-02-09 02:05:28,2015-02-09 03:03:37,4372,thai,2.00,3,2660,3,195,925,89.00,75.00,145.00,251,708.00,False,False,False,False,False,"3,489.00",2015-02-08 18:05:28-08:00,18,6
145575,2.00,2015-02-07 02:21:32,2015-02-07 03:33:28,1871,japanese,1.00,5,3475,4,195,1395,151.00,117.00,214.00,446,746.00,False,False,False,False,False,"4,316.00",2015-02-06 18:21:32-08:00,18,4
52456,6.00,2015-02-18 03:58:18,2015-02-18 04:35:06,667,catering,1.00,2,4390,1,1495,1495,60.00,49.00,49.00,251,573.00,False,False,False,False,False,"2,208.00",2015-02-17 19:58:18-08:00,19,1

# Feature Engineering

## Drop unneeded columns

In [18]:
# Drop market_id_imputed (real-world conditional fill, no longer needed as signal)
# Drop raw UTC created_at (superseded by created_at_local) and actual_delivery_time
# (target is already computed as total_delivery_duration; keeping actual_delivery_time
# around risks accidental leakage in later exploratory code)
df = df.drop(columns=["market_id_imputed", "store_category_imputed", "created_at", "actual_delivery_time"])
df.shape

(195788, 21)

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 195788 entries, 0 to 195787
Data columns (total 21 columns):
 #   Column                                        Non-Null Count   Dtype
---  ------                                        --------------   -----
 0   market_id                                     195788 non-null  float64
 1   store_id                                      195788 non-null  int64
 2   store_primary_category                        195788 non-null  str
 3   order_protocol                                195788 non-null  float64
 4   total_items                                   195788 non-null  int64
 5   subtotal                                      195788 non-null  int64
 6   num_distinct_items                            195788 non-null  int64
 7   min_item_price                                195788 non-null  int64
 8   max_item_price                                195788 non-null  int64
 9   total_onshift_dashers                         195788 non-null  float64
 10  total_busy_dashers                            195788 non-null  float64
 11  total_outstanding_orders                      195788 non-null  float64
 12  estimated_order_place_duration                195788 non-null  int64
 13  estimated_store_to_consumer_driving_duration  195788 non-null  float64
 14  total_onshift_dashers_imputed                 195788 non-null  bool
 15  total_busy_dashers_imputed                    195788 non-null  bool
 16  total_outstanding_orders_imputed              195788 non-null  bool
 17  total_delivery_duration                       195788 non-null  float64
 18  created_at_local                              195788 non-null  datetime64[us, US/Pacific]
 19  order_hour                                    195788 non-null  int32
 20  order_day_of_week                             195788 non-null  int32
dtypes: bool(3), datetime64[us, US/Pacific](1), float64(7), int32(2), int64(7), str(1)
memory usage: 27.3 MB

## Create busy_dasher_ratio and outstanding_order_ratio features

In [20]:
zero_onshift = df["total_onshift_dashers"] == 0
print(f"Rows with onshift==0: {zero_onshift.sum()} ({zero_onshift.mean():.4%})")

# What do busy/outstanding look like when onshift==0?
df.loc[zero_onshift, ["total_busy_dashers", "total_outstanding_orders", "total_delivery_duration"]].describe()

# Compare delivery duration for onshift==0 vs the rest
print("Median duration, onshift==0:", df.loc[zero_onshift, "total_delivery_duration"].median())
print("Median duration, onshift>0: ", df.loc[~zero_onshift, "total_delivery_duration"].median())

Rows with onshift==0: 3540 (1.8081%)

       total_busy_dashers  total_outstanding_orders  total_delivery_duration
count            3,540.00                  3,540.00                 3,540.00
mean                 0.04                      0.12                 3,257.17
std                  0.84                      0.70                 1,179.01
min                 -4.00                      0.00                   960.00
25%                  0.00                      0.00                 2,374.75
50%                  0.00                      0.00                 3,067.00
75%                  0.00                      0.00                 3,941.00
max                 29.00                     13.00                 7,169.00

Median duration, onshift==0: 3067.0
Median duration, onshift>0:  2648.0

In [21]:
# Raw ratio, NaN where onshift == 0
raw_busy_ratio = df["total_busy_dashers"] / df["total_onshift_dashers"].replace(0, np.nan)
raw_outstanding_ratio = df["total_outstanding_orders"] / df["total_onshift_dashers"].replace(0, np.nan)

# Empirical 99th percentile of the *valid* (non-zero-onshift) ratio distribution
busy_p99 = raw_busy_ratio.quantile(0.99)
outstanding_p99 = raw_outstanding_ratio.quantile(0.99)

busy_cap = busy_p99 * 2  # generous cap for the "impossible/undefined" onshift=0 case
outstanding_cap = outstanding_p99 * 2

print(f"busy_ratio p99={busy_p99:.3f} -> cap={busy_cap:.3f}")
print(f"outstanding_ratio p99={outstanding_p99:.3f} -> cap={outstanding_cap:.3f}")

df["busy_dasher_ratio"] = raw_busy_ratio.fillna(busy_cap)
df["outstanding_order_ratio"] = raw_outstanding_ratio.fillna(outstanding_cap)

# sanity checks
(df["total_onshift_dashers"] == 0).sum()
df[["busy_dasher_ratio", "outstanding_order_ratio"]].describe()

busy_ratio p99=1.964 -> cap=3.929
outstanding_ratio p99=2.286 -> cap=4.571

np.int64(3540)

       busy_dasher_ratio  outstanding_order_ratio
count         195,788.00               195,788.00
mean                1.00                     1.28
std                 0.55                     0.64
min               -13.00                   -16.00
25%                 0.84                     0.96
50%                 0.96                     1.21
75%                 1.00                     1.47
max                31.00                    47.00

## Time-based train/test split

In [22]:
# Row-count-based split can slice unevenly across days when order volume varies by day-of-week. Switch to a calendar-day cutoff instead.
df["order_date"] = df["created_at_local"].dt.date

unique_dates = sorted(df["order_date"].unique())
print(f"Total unique dates: {len(unique_dates)}")
print(unique_dates)

Total unique dates: 28
[datetime.date(2015, 1, 21), datetime.date(2015, 1, 22), datetime.date(2015, 1, 23), datetime.date(2015, 1, 24), datetime.date(2015, 1, 25), datetime.date(2015, 1, 26), datetime.date(2015, 1, 27), datetime.date(2015, 1, 28), datetime.date(2015, 1, 29), datetime.date(2015, 1, 30), datetime.date(2015, 1, 31), datetime.date(2015, 2, 1), datetime.date(2015, 2, 2), datetime.date(2015, 2, 3), datetime.date(2015, 2, 4), datetime.date(2015, 2, 5), datetime.date(2015, 2, 6), datetime.date(2015, 2, 7), datetime.date(2015, 2, 8), datetime.date(2015, 2, 9), datetime.date(2015, 2, 10), datetime.date(2015, 2, 11), datetime.date(2015, 2, 12), datetime.date(2015, 2, 13), datetime.date(2015, 2, 14), datetime.date(2015, 2, 15), datetime.date(2015, 2, 16), datetime.date(2015, 2, 17)]

In [23]:
# Time-based train/test split (must happen before target encoding)
# Split on a calendar-day boundary so no individual day is split
# between train and test.

df = df.sort_values("created_at_local").reset_index(drop=True)

cutoff_date = pd.Timestamp("2015-02-11").date()

df["is_train"] = df["order_date"] < cutoff_date

print(f"Cutoff date: {cutoff_date}")
print(f"Train rows: {df['is_train'].sum()} ({df['is_train'].mean():.2%})")
print(f"Test rows:  {(~df['is_train']).sum()} ({(~df['is_train']).mean():.2%})")
print(
    f"Train date range: "
    f"{df.loc[df['is_train'], 'created_at_local'].min()} -> "
    f"{df.loc[df['is_train'], 'created_at_local'].max()}"
)
print(
    f"Test date range:  "
    f"{df.loc[~df['is_train'], 'created_at_local'].min()} -> "
    f"{df.loc[~df['is_train'], 'created_at_local'].max()}"
)

Cutoff date: 2015-02-11
Train rows: 143468 (73.28%)
Test rows:  52320 (26.72%)
Train date range: 2015-01-21 07:22:03-08:00 -> 2015-02-10 22:00:27-08:00
Test date range:  2015-02-11 06:41:00-08:00 -> 2015-02-17 22:00:44-08:00

In [24]:
# Sanity check: does the test window span a weekend, and is day-of-week representation reasonable in both splits?
train_dow = df.loc[df["is_train"], "order_day_of_week"].value_counts(normalize=True).sort_index()
test_dow = df.loc[~df["is_train"], "order_day_of_week"].value_counts(normalize=True).sort_index()

pd.DataFrame({"train": train_dow, "test": test_dow})

                   train  test
order_day_of_week
0                   0.13  0.12
1                   0.12  0.12
2                   0.13  0.13
3                   0.14  0.14
4                   0.17  0.16
5                   0.17  0.16
6                   0.15  0.17

## Target encoding: store_primary_category

In [25]:
# Target encoding: store_primary_category (fit on train only)
# Smoothed target encoding to avoid overfitting on rare/low-count categories.
# Formula: (category_mean * n + global_mean * smoothing) / (n + smoothing)
# Higher smoothing pulls sparse categories harder toward the global mean.

SMOOTHING = 20  # weight of the prior; tune later if needed

global_mean = df.loc[df["is_train"], "total_delivery_duration"].mean()

category_stats = (
    df.loc[df["is_train"]]
    .groupby("store_primary_category")["total_delivery_duration"]
    .agg(["mean", "count"])
)

category_stats["smoothed_mean"] = (
        (category_stats["mean"] * category_stats["count"] + global_mean * SMOOTHING)
        / (category_stats["count"] + SMOOTHING)
)

category_encoding_map = category_stats["smoothed_mean"].to_dict()

# Apply to full dataframe (train and test both use the train-fit map).
# Any category in test not seen in train falls back to global_mean.
df["store_category_target_enc"] = (
    df["store_primary_category"]
    .map(category_encoding_map)
    .fillna(global_mean)
)

print(f"Global mean (train): {global_mean:.1f}")
print(f"Categories encoded: {len(category_encoding_map)}")
category_stats.sort_values("count").head(10)

Global mean (train): 2804.8
Categories encoded: 75

                           mean  count  smoothed_mean
store_primary_category
alcohol-plus-food      3,046.00      1       2,816.28
chocolate              2,048.00      1       2,768.75
belgian                2,710.00      1       2,800.28
indonesian             2,445.00      2       2,772.08
lebanese               3,027.29      7       2,862.48
african                3,064.33      9       2,885.34
european               2,691.36     11       2,764.54
russian                3,141.15     13       2,937.30
cheese                 3,079.00     15       2,922.31
comfort-food           2,785.45     20       2,795.12

In [26]:
# Verify no leakage: encoding values should be identical whether computed
# from train alone or from train+test slices of the map (they're the same map)
df[["store_primary_category", "store_category_target_enc"]].drop_duplicates().sort_values(
    "store_category_target_enc").head()
df[["store_primary_category", "store_category_target_enc"]].drop_duplicates().sort_values(
    "store_category_target_enc").tail()

     store_primary_category  store_category_target_enc
1433            gluten-free                   2,553.85
9                      fast                   2,596.08
1227      convenience-store                   2,605.68
6                   mexican                   2,631.69
11                 sandwich                   2,635.10

     store_primary_category  store_category_target_enc
702                   cajun                   3,078.62
1101                burmese                   3,083.58
840               brazilian                   3,122.48
1032                  tapas                   3,125.37
405               caribbean                   3,175.67

## Cyclical encoding: order_hour and order_day_of_week

In [27]:
# Cyclical encoding: order_hour and order_day_of_week
# Raw integers imply hour=23 is far from hour=0, which is wrong for delivery
# timing (late-night orders near midnight should be treated as adjacent hours).
df["hour_sin"] = np.sin(2 * np.pi * df["order_hour"] / 24)
df["hour_cos"] = np.cos(2 * np.pi * df["order_hour"] / 24)

df["dow_sin"] = np.sin(2 * np.pi * df["order_day_of_week"] / 7)
df["dow_cos"] = np.cos(2 * np.pi * df["order_day_of_week"] / 7)

df[["order_hour", "hour_sin", "hour_cos", "order_day_of_week", "dow_sin", "dow_cos"]].sample(8)

        order_hour  hour_sin  hour_cos  order_day_of_week  dow_sin  dow_cos
23737           17     -0.97     -0.26                  5    -0.97    -0.22
806             12      0.00     -1.00                  2     0.97    -0.22
31553           17     -0.97     -0.26                  6    -0.78     0.62
17058           18     -1.00     -0.00                  4    -0.43    -0.90
2128            16     -0.87     -0.50                  2     0.97    -0.22
140928          18     -1.00     -0.00                  1     0.78     0.62
153603          17     -0.97     -0.26                  3     0.43    -0.90
75746           16     -0.87     -0.50                  6    -0.78     0.62

## Target transform candidates

In [28]:
# Target transform candidates (decide log vs. raw empirically in model_training.ipynb)
df["target_raw"] = df["total_delivery_duration"]
df["target_log1p"] = np.log1p(df["total_delivery_duration"])

df[["target_raw", "target_log1p"]].describe()

       target_raw  target_log1p
count  195,788.00    195,788.00
mean     2,826.50          7.89
std      1,016.05          0.35
min        223.00          5.41
25%      2,101.00          7.65
50%      2,654.00          7.88
75%      3,366.00          8.12
max      7,196.00          8.88

## Final feature set review before export

In [29]:
# Drop the now-redundant intermediate columns:
# - store_primary_category: superseded by store_category_target_enc
# - order_hour, order_day_of_week: superseded by sin/cos pairs
# - created_at_local: was only needed for the split; a GBDT gets no use from a raw timestamp, and keeping it around risks accidental leakage if someone derives new time features downstream without re-checking the split
# - total_delivery_duration: kept as target_raw / target_log1p instead

final_drop_cols = [
    "store_primary_category",
    "order_hour",
    "order_day_of_week",
    "created_at_local",
    "total_delivery_duration",
]
df = df.drop(columns=final_drop_cols)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 195788 entries, 0 to 195787
Data columns (total 27 columns):
 #   Column                                        Non-Null Count   Dtype
---  ------                                        --------------   -----
 0   market_id                                     195788 non-null  float64
 1   store_id                                      195788 non-null  int64
 2   order_protocol                                195788 non-null  float64
 3   total_items                                   195788 non-null  int64
 4   subtotal                                      195788 non-null  int64
 5   num_distinct_items                            195788 non-null  int64
 6   min_item_price                                195788 non-null  int64
 7   max_item_price                                195788 non-null  int64
 8   total_onshift_dashers                         195788 non-null  float64
 9   total_busy_dashers                            195788 non-null  float64
 10  total_outstanding_orders                      195788 non-null  float64
 11  estimated_order_place_duration                195788 non-null  int64
 12  estimated_store_to_consumer_driving_duration  195788 non-null  float64
 13  total_onshift_dashers_imputed                 195788 non-null  bool
 14  total_busy_dashers_imputed                    195788 non-null  bool
 15  total_outstanding_orders_imputed              195788 non-null  bool
 16  busy_dasher_ratio                             195788 non-null  float64
 17  outstanding_order_ratio                       195788 non-null  float64
 18  order_date                                    195788 non-null  object
 19  is_train                                      195788 non-null  bool
 20  store_category_target_enc                     195788 non-null  float64
 21  hour_sin                                      195788 non-null  float64
 22  hour_cos                                      195788 non-null  float64
 23  dow_sin                                       195788 non-null  float64
 24  dow_cos                                       195788 non-null  float64
 25  target_raw                                    195788 non-null  float64
 26  target_log1p                                  195788 non-null  float64
dtypes: bool(4), float64(15), int64(7), object(1)
memory usage: 35.1+ MB

In [30]:
df.sample(10)

,market_id,store_id,order_protocol,total_items,subtotal,num_distinct_items,min_item_price,max_item_price,total_onshift_dashers,total_busy_dashers,total_outstanding_orders,estimated_order_place_duration,estimated_store_to_consumer_driving_duration,total_onshift_dashers_imputed,total_busy_dashers_imputed,total_outstanding_orders_imputed,busy_dasher_ratio,outstanding_order_ratio,order_date,is_train,store_category_target_enc,hour_sin,hour_cos,dow_sin,dow_cos,target_raw,target_log1p
159936,4.00,561,1.00,5,3910,5,225,945,11.00,3.00,3.00,446,298.00,False,False,False,0.27,0.27,2015-02-13,False,"2,980.48",-0.87,-0.50,-0.43,-0.90,"2,620.00",7.87
62282,4.00,4411,1.00,1,899,1,899,899,64.00,54.00,104.00,446,411.00,False,False,False,0.84,1.62,2015-01-30,True,"2,811.31",-1.00,-0.00,-0.43,-0.90,"2,773.00",7.93
7212,4.00,4863,3.00,2,2500,2,600,1075,57.00,61.00,93.00,251,905.00,False,False,False,1.07,1.63,2015-01-22,True,"2,716.50",0.00,-1.00,0.43,-0.90,"2,690.00",7.90
26812,2.00,5839,5.00,2,2853,2,1099,1479,93.00,102.00,157.00,251,404.00,False,False,False,1.10,1.69,2015-01-24,True,"2,987.60",-0.97,0.26,-0.97,-0.22,"3,816.00",8.25
11010,4.00,194,1.00,3,2070,3,325,995,98.00,93.00,143.00,446,538.00,False,False,False,0.95,1.46,2015-01-22,True,"2,959.68",-0.97,0.26,0.43,-0.90,"2,671.00",7.89
52481,1.00,4710,4.00,7,1795,4,100,640,6.00,12.00,16.00,251,336.00,False,False,False,2.00,2.67,2015-01-29,True,"2,596.08",-0.50,-0.87,0.43,-0.90,"1,390.00",7.24
164184,5.00,4343,5.00,5,2630,5,195,895,61.00,60.00,113.00,251,408.00,False,False,False,0.98,1.85,2015-02-13,False,"2,688.70",-0.97,0.26,-0.43,-0.90,"3,052.00",8.02
192174,4.00,326,2.00,3,3140,3,795,1450,59.00,57.00,73.00,251,672.00,False,False,False,0.97,1.24,2015-02-17,False,"2,728.58",-0.87,-0.50,0.78,0.62,"6,096.00",8.72
1302,6.00,6386,1.00,1,895,1,895,895,29.00,26.50,30.00,446,349.00,True,True,True,0.91,1.03,2015-01-21,True,"2,781.04",-0.26,-0.97,0.97,-0.22,"1,936.00",7.57
74695,2.00,2687,3.00,2,1690,2,795,895,60.00,64.00,79.00,251,795.00,False,False,False,1.07,1.32,2015-02-01,True,"2,823.11",-0.50,-0.87,-0.78,0.62,"2,326.00",7.75

## Export processed data

In [31]:
# Export
df.to_csv("../dataset/processed/processed_data.csv", index=False)
df.to_parquet("../dataset/processed/processed_data.parquet", index=False)

# Export target encoding mapping and global mean for model bundle & deployment
joblib.dump(
    {
        "category_encoding_map": category_encoding_map,
        "global_mean": global_mean
    },
    "../dataset/processed/category_target_encoding.joblib"
)

print(f"Exported {df.shape[0]} rows, {df.shape[1]} columns")
print(f"Exported target encoding map ({len(category_encoding_map)} categories) to ../dataset/processed/category_target_encoding.joblib")

['../dataset/processed/category_target_encoding.joblib']

Exported 195788 rows, 27 columns
Exported target encoding map (75 categories) to ../dataset/processed/category_target_encoding.joblib