In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_parquet('../dataset/processed/merged_data.parquet')

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 456548 entries, 0 to 456547
Data columns (total 15 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   id                     456548 non-null  int64
 1   week                   456548 non-null  int64
 2   center_id              456548 non-null  int64
 3   meal_id                456548 non-null  int64
 4   checkout_price         456548 non-null  float64
 5   base_price             456548 non-null  float64
 6   emailer_for_promotion  456548 non-null  int64
 7   homepage_featured      456548 non-null  int64
 8   num_orders             456548 non-null  int64
 9   city_code              456548 non-null  int64
 10  region_code            456548 non-null  int64
 11  center_type            456548 non-null  str
 12  op_area                456548 non-null  float64
 13  category               456548 non-null  str
 14  cuisine                456548 non-null  str
dtypes: float64(3), int64(9), str(3)
memory usage: 61.1 MB

In [5]:
print("Unique centers:", df['center_id'].nunique())
print("Unique meals:", df['meal_id'].nunique())
print("Unique weeks:", df['week'].nunique())

print("\nWeek range:")
print(df['week'].min(), "to", df['week'].max())

Unique centers: 77
Unique meals: 51
Unique weeks: 145

Week range:
1 to 145

Reindex the panel to a full (center_id, meal_id, week) grid.

Why: the raw data only has a row when a meal was actually ordered.
A missing row does NOT mean "unknown" — it means the meal had 0 orders that week. If we don't fill these gaps, later lag/rolling features (e.g. "orders last week") will silently pull from the wrong week whenever there's a gap, corrupting the feature without any error.

In [6]:
min_week, max_week = df['week'].min(), df['week'].max()
full_weeks = pd.DataFrame({'week': range(min_week, max_week + 1)})

print(f"Full week range: {min_week} to {max_week} ({len(full_weeks)} weeks)")

Full week range: 1 to 145 (145 weeks)

Only reindex pairs that actually existed at least once in the data. We do NOT want to invent center-meal combinations that never happened (e.g. a meal a center never sells).

In [7]:
real_pairs=df[['center_id', 'meal_id']].drop_duplicates()
len(real_pairs)

3597

In [8]:
full_grid=full_weeks.merge(real_pairs, how='cross')
full_grid.shape

(521565, 3)

In [9]:
full_grid.head()

   week  center_id  meal_id
0     1         55     1885
1     1         55     1993
2     1         55     2539
3     1         55     2139
4     1         55     2631

In [10]:
df_full=full_grid.merge(df, how='left', on=['center_id', 'meal_id', 'week'])

In [11]:
df_full.isnull().sum()

week                         0
center_id                    0
meal_id                      0
id                       65017
checkout_price           65017
base_price               65017
emailer_for_promotion    65017
homepage_featured        65017
num_orders               65017
city_code                65017
region_code              65017
center_type              65017
op_area                  65017
category                 65017
cuisine                  65017
dtype: int64

In [12]:
df_full['num_orders']=df_full['num_orders'].fillna(0)

In [13]:
df_full.isnull().sum()

week                         0
center_id                    0
meal_id                      0
id                       65017
checkout_price           65017
base_price               65017
emailer_for_promotion    65017
homepage_featured        65017
num_orders                   0
city_code                65017
region_code              65017
center_type              65017
op_area                  65017
category                 65017
cuisine                  65017
dtype: int64

In [14]:
df_full=df_full.drop(columns='id')

In [15]:
df_full.info()

<class 'pandas.DataFrame'>
RangeIndex: 521565 entries, 0 to 521564
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   week                   521565 non-null  int64
 1   center_id              521565 non-null  int64
 2   meal_id                521565 non-null  int64
 3   checkout_price         456548 non-null  float64
 4   base_price             456548 non-null  float64
 5   emailer_for_promotion  456548 non-null  float64
 6   homepage_featured      456548 non-null  float64
 7   num_orders             521565 non-null  float64
 8   city_code              456548 non-null  float64
 9   region_code            456548 non-null  float64
 10  center_type            456548 non-null  str
 11  op_area                456548 non-null  float64
 12  category               456548 non-null  str
 13  cuisine                456548 non-null  str
dtypes: float64(8), int64(3), str(3)
memory usage: 64.8 MB

In [16]:
df_full=df_full.sort_values(by=['center_id', 'meal_id', 'week']).reset_index(drop=True)

In [17]:
static_cols=['city_code', 'region_code', 'center_type', 'op_area', 'category', 'cuisine']

In [18]:
for col in static_cols:
    df_full[col]=(df_full.groupby(['center_id', 'meal_id'])[col].transform(lambda s: s.ffill().bfill()))

In [19]:
df_full.isnull().sum()

week                         0
center_id                    0
meal_id                      0
checkout_price           65017
base_price               65017
emailer_for_promotion    65017
homepage_featured        65017
num_orders                   0
city_code                    0
region_code                  0
center_type                  0
op_area                      0
category                     0
cuisine                      0
dtype: int64

In [20]:
price_cols=['base_price', 'checkout_price']

In [21]:
for col in price_cols:
    df_full[col]=(df_full.groupby(['center_id', 'meal_id'])[col].transform(lambda s: s.ffill().bfill()))

In [22]:
df_full.isnull().sum()

week                         0
center_id                    0
meal_id                      0
checkout_price               0
base_price                   0
emailer_for_promotion    65017
homepage_featured        65017
num_orders                   0
city_code                    0
region_code                  0
center_type                  0
op_area                      0
category                     0
cuisine                      0
dtype: int64

In [23]:
df_full['emailer_for_promotion']=df_full['emailer_for_promotion'].fillna(0).astype(int)
df_full['homepage_featured']=df_full['homepage_featured'].fillna(0).astype(int)

In [24]:
df_full.isnull().sum()

week                     0
center_id                0
meal_id                  0
checkout_price           0
base_price               0
emailer_for_promotion    0
homepage_featured        0
num_orders               0
city_code                0
region_code              0
center_type              0
op_area                  0
category                 0
cuisine                  0
dtype: int64

In [25]:
df_full.shape

(521565, 14)

### Target transform: compress the long right tail so the model doesn't overweight a handful of huge center-meal combos. +1 handles the genuine zeros we just created via reindexing (log(0) is undefined).

In [26]:
# log1p(1+x)=log(1+x)
df_full['log_num_orders']=np.log1p(df_full['num_orders'])

In [27]:
df_full.head()

,week,center_id,meal_id,checkout_price,base_price,emailer_for_promotion,homepage_featured,num_orders,city_code,region_code,center_type,op_area,category,cuisine,log_num_orders
0,1,10,1062,181.39,181.39,0,0,865.0,590.0,56.0,TYPE_B,6.3,Beverages,Italian,6.763885
1,2,10,1062,183.36,182.36,0,0,782.0,590.0,56.0,TYPE_B,6.3,Beverages,Italian,6.663133
2,3,10,1062,184.36,182.36,0,0,851.0,590.0,56.0,TYPE_B,6.3,Beverages,Italian,6.747587
3,4,10,1062,182.36,183.36,0,0,1202.0,590.0,56.0,TYPE_B,6.3,Beverages,Italian,7.092574
4,5,10,1062,183.39,181.39,0,0,958.0,590.0,56.0,TYPE_B,6.3,Beverages,Italian,6.865891

### Lag: all built on the SHIFTED series so no row ever sees its own current-week value. Group by (center_id, meal_id) so features never leak across different centers or meals.

In [28]:
df_full=df_full.sort_values(['center_id', 'meal_id', 'week']).reset_index(drop=True)

In [29]:
grp=df_full.groupby(['center_id', 'meal_id'])['log_num_orders']

In [30]:
df_full['lag_1']=grp.shift(1)
df_full['lag_2']=grp.shift(2)
df_full['lag_4']=grp.shift(4)

In [31]:
df_full.head()

,week,center_id,meal_id,checkout_price,base_price,emailer_for_promotion,homepage_featured,num_orders,city_code,region_code,center_type,op_area,category,cuisine,log_num_orders,lag_1,lag_2,lag_4
0,1,10,1062,181.39,181.39,0,0,865.0,590.0,56.0,TYPE_B,6.3,Beverages,Italian,6.763885,NaN,NaN,NaN
1,2,10,1062,183.36,182.36,0,0,782.0,590.0,56.0,TYPE_B,6.3,Beverages,Italian,6.663133,6.763885,NaN,NaN
2,3,10,1062,184.36,182.36,0,0,851.0,590.0,56.0,TYPE_B,6.3,Beverages,Italian,6.747587,6.663133,6.763885,NaN
3,4,10,1062,182.36,183.36,0,0,1202.0,590.0,56.0,TYPE_B,6.3,Beverages,Italian,7.092574,6.747587,6.663133,NaN
4,5,10,1062,183.39,181.39,0,0,958.0,590.0,56.0,TYPE_B,6.3,Beverages,Italian,6.865891,7.092574,6.747587,6.763885

### Rolling features: always shift(1) FIRST, then roll

In [32]:
shifted=grp.shift(1)

In [33]:
df_full['rolling_mean_4']=shifted.groupby([df_full['center_id'], df_full['meal_id']]).transform(lambda x: x.rolling(window=4, min_periods=1).mean())

In [34]:
df_full['rolling_std_4']=shifted.groupby([df_full['center_id'], df_full['meal_id']]).transform(lambda x: x.rolling(window=4, min_periods=1).std())

In [35]:
df_full.head()

,week,center_id,meal_id,checkout_price,base_price,emailer_for_promotion,homepage_featured,num_orders,city_code,region_code,center_type,op_area,category,cuisine,log_num_orders,lag_1,lag_2,lag_4,rolling_mean_4,rolling_std_4
0,1,10,1062,181.39,181.39,0,0,865.0,590.0,56.0,TYPE_B,6.3,Beverages,Italian,6.763885,NaN,NaN,NaN,NaN,NaN
1,2,10,1062,183.36,182.36,0,0,782.0,590.0,56.0,TYPE_B,6.3,Beverages,Italian,6.663133,6.763885,NaN,NaN,6.763885,NaN
2,3,10,1062,184.36,182.36,0,0,851.0,590.0,56.0,TYPE_B,6.3,Beverages,Italian,6.747587,6.663133,6.763885,NaN,6.713509,0.071243
3,4,10,1062,182.36,183.36,0,0,1202.0,590.0,56.0,TYPE_B,6.3,Beverages,Italian,7.092574,6.747587,6.663133,NaN,6.724868,0.054082
4,5,10,1062,183.39,181.39,0,0,958.0,590.0,56.0,TYPE_B,6.3,Beverages,Italian,6.865891,7.092574,6.747587,6.763885,6.816794,0.189081

Fill NaNs in lag/rolling features with 0.
Rationale: a NaN here means "this center-meal pair doesn't have enough history yet" (new meal/center, or early weeks of the panel). We assume "no prior history" = "no prior demand observed" = 0. This is a modeling choice, not a fact — it deliberately keeps cold-start rows in training so the model learns to handle new center-meal pairs, rather than only ever seeing pairs with an established order history.

In [36]:
lag_roll_cols=['lag_1', 'lag_2', 'lag_4', 'rolling_mean_4', 'rolling_std_4']

In [37]:
# Add a flag so the model can distinguish "genuinely 0 prior demand" from "0 because we're filling missing history"
df_full['new_centre_meal']=df_full['lag_4'].isna().astype(int)

In [38]:
for col in lag_roll_cols:
    df_full[col] = df_full[col].fillna(0)

In [39]:
df_full.head(10)

,week,center_id,meal_id,checkout_price,base_price,emailer_for_promotion,homepage_featured,num_orders,city_code,region_code,...,op_area,category,cuisine,log_num_orders,lag_1,lag_2,lag_4,rolling_mean_4,rolling_std_4,new_centre_meal
0,1,10,1062,181.39,181.39,0,0,865.0,590.0,56.0,...,6.3,Beverages,Italian,6.763885,0.000000,0.000000,0.000000,0.000000,0.000000,1
1,2,10,1062,183.36,182.36,0,0,782.0,590.0,56.0,...,6.3,Beverages,Italian,6.663133,6.763885,0.000000,0.000000,6.763885,0.000000,1
2,3,10,1062,184.36,182.36,0,0,851.0,590.0,56.0,...,6.3,Beverages,Italian,6.747587,6.663133,6.763885,0.000000,6.713509,0.071243,1
3,4,10,1062,182.36,183.36,0,0,1202.0,590.0,56.0,...,6.3,Beverages,Italian,7.092574,6.747587,6.663133,0.000000,6.724868,0.054082,1
4,5,10,1062,183.39,181.39,0,0,958.0,590.0,56.0,...,6.3,Beverages,Italian,6.865891,7.092574,6.747587,6.763885,6.816794,0.189081,0
5,6,10,1062,162.05,183.39,0,0,1094.0,590.0,56.0,...,6.3,Beverages,Italian,6.998510,6.865891,7.092574,6.663133,6.842296,0.186427,0
6,7,10,1062,160.08,183.39,0,0,1513.0,590.0,56.0,...,6.3,Beverages,Italian,7.322510,6.998510,6.865891,6.747587,6.926140,0.151051,0
7,8,10,1062,160.05,182.39,0,0,1149.0,590.0,56.0,...,6.3,Beverages,Italian,7.047517,7.322510,6.998510,7.092574,7.069871,0.192391,0
8,9,10,1062,162.05,182.39,0,0,1282.0,590.0,56.0,...,6.3,Beverages,Italian,7.156956,7.047517,7.322510,6.865891,7.058607,0.191937,0
9,10,10,1062,161.05,181.39,0,0,1473.0,590.0,56.0,...,6.3,Beverages,Italian,7.295735,7.156956,7.047517,6.998510,7.131373,0.143611,0

In [40]:
# Captures annual seasonality (weeks 1 to 52)
df_full['week_of_year'] = ((df_full['week']-1) % 52) + 1

In [41]:
# negative = discount, positive = markup
df_full['price_change_pct'] = (df_full['checkout_price'] - df_full['base_price']) / df_full['base_price']

In [42]:
df_full.head()

,week,center_id,meal_id,checkout_price,base_price,emailer_for_promotion,homepage_featured,num_orders,city_code,region_code,...,cuisine,log_num_orders,lag_1,lag_2,lag_4,rolling_mean_4,rolling_std_4,new_centre_meal,week_of_year,price_change_pct
0,1,10,1062,181.39,181.39,0,0,865.0,590.0,56.0,...,Italian,6.763885,0.000000,0.000000,0.000000,0.000000,0.000000,1,1,0.000000
1,2,10,1062,183.36,182.36,0,0,782.0,590.0,56.0,...,Italian,6.663133,6.763885,0.000000,0.000000,6.763885,0.000000,1,2,0.005484
2,3,10,1062,184.36,182.36,0,0,851.0,590.0,56.0,...,Italian,6.747587,6.663133,6.763885,0.000000,6.713509,0.071243,1,3,0.010967
3,4,10,1062,182.36,183.36,0,0,1202.0,590.0,56.0,...,Italian,7.092574,6.747587,6.663133,0.000000,6.724868,0.054082,1,4,-0.005454
4,5,10,1062,183.39,181.39,0,0,958.0,590.0,56.0,...,Italian,6.865891,7.092574,6.747587,6.763885,6.816794,0.189081,0,5,0.011026

In [43]:
df_full.to_parquet('../dataset/processed/feature_engineered_data.parquet', index=False)